[server]
headless = true

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#005eb8"
backgroundColor = "#f4f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#102a43"
font = "sans serif"
